name: .NET Test with xUnit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Change if needed

    - name: Restore dependencies
      run: dotnet restore ConsoleProject/ConsoleProject.sln  # Adjust path to your .sln or .csproj file

    - name: Build the project
      run: dotnet build ConsoleProject/ConsoleProject.sln --no-restore --configuration Release

    - name: Run xUnit tests
      run: dotnet test ConsoleProject/ConsoleProject.sln --no-build --configuration Release
